version: '2'

services:
  dhcpd:
    image: ictu/docker-dhcpd
    restart: always
    networks:
      public:
        ipv4_address: 10.25.80.1
    environment:
      - "SERVER_IP=10.25.80.1"
      - "GATEWAY=10.25.80.254"
      - "SUBNET=10.25.80.0"
      - "NETMASK=255.255.255.0"
      - "RANGE_PXE=10.25.80.21 10.25.80.40"
      - "RANGE_STATIC=10.25.80.41 10.25.80.50"
      - "RANGE_OTHER=10.25.80.51 10.25.80.240"
      - "NAMESERVERS=10.25.55.2,10.25.55.3"
      - "DEFAULT_LEASE_TIME=60"
      - "MAX_LEASE_TIME=180"
  
networks:
  public:
    external:
      name: mcv3080
